apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'example-app'
        static_configs:
          - targets: ['example-app:5000']

    alerting:
      alertmanagers:
        - static_configs:
          - targets: ['alertmanager-config:9093']
